### ISSUE TITLE
vitest vs chai type expect / toEqual

### ISSUE THREAD

**Issue by pieterjandebruyne** [total-typescript/typescript-generics-workshop#20]
When running npm install, it installs @types/chai. Because of this my IDE (webstorm) is using the chai declaration of expect (which does not have toEqual) instead of vitest types. Do we actually need to install those chai types? deleting them seems to fix the issue.

**Comment by MehdiRaash** [comment]
asking for my curiosity, What's the reason on using Webstorm? ;-)

**Comment by mattpocock** [comment]
Yep, don't install those chai types!
